name: Tests
on:
    push:
        branches:
            - main
        paths:
            - 'packages/**'
            - 'tests/**'
            - 'package-lock.json'
            - '.github/workflows/tests.yml'
    pull_request:
        paths:
            - 'packages/**'
            - 'tests/**'
            - 'package-lock.json'
            - '.github/workflows/tests.yml'

defaults:
    run:
        shell: 'bash'

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'pnpm'
            - run: pnpm install
            - run: pnpm run test:main

    preload:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'pnpm'
            - run: pnpm install
            - run: pnpm run test:preload

    renderer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'pnpm'
            - run: pnpm install
            - run: pnpm run test:renderer

    e2e:
        strategy:
            fail-fast: false
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'pnpm'
            - run: pnpm install
            - run: pnpx playwright install --with-deps
            - run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- pnpm run test:e2e
              if: matrix.os == 'ubuntu-latest'
            - run: pnpm run test:e2e
              if: matrix.os != 'ubuntu-latest'
